Map<String, String> arLang = {
  'signUp': 'قم بالتسجيل',
  'signup_title': 'إنشاء حساب عن طريق ملىء التفاصيل التالية',
  'lorem_ipsum': 'لوريم إيبسوم',
  'first_name': 'الاسم الأول',
  'last_name': 'الاسم الأخير',
  'mobile_number': 'رقم الجوال',
  'country': 'الدولة',
  'password': 'كلمة المرور',
  'confirm_password': 'تأكيد كلمة المرور',
  'signIn': 'تسجيل الدخول',
  'already_have_account': 'هل لديك حساب بالفعل؟',
  'email_address': 'عنوان البريد الإلكتروني',
  'verify_code': 'التحقق من الكود',
  'please_check_verification':
      'من فضلك، تحقق من بريدك الإلكتروني لقد أرسلنا لك الرمز على',
  'Premium': 'قسط',
  'password_validation':
      'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل، وحرف كبير واحد، ورقم واحد، ورمز خاص واحد',
  'subscribe_newsletter': 'اشترك في النشرة الإخبارية لدينا...',
  'agree_all': 'أوافق على كل',
  'term_condition': 'الشروط والأحكام',
  'welcome_back': 'مرحبا بعودتك!',
  'signin_title': 'تحتاج إلى تسجيل الدخول باستخدام بيانات الاعتماد الخاصة بك',
  'dont_have_account': 'ليس لديك حساب؟',
  'create_now': 'أنشئ الآن',
  'forgot_password': 'نسيت كلمة المرور',
  'Service Provider (SP)': 'مزود الخدمة (SP)',
  'Service Receiver (SR)': 'جهاز استقبال الخدمة (SR)',
  'ON it Wallet': 'على ذلك المحفظة',
  'ONit Portfolio': 'محفظة ONit',
  'my_services': 'خدماتي',
  'my_bids': 'عطاءاتي',
  'Browse Service →': 'تصفح الخدمة →',
  'Story Telling': 'روايتك',
  'Pro Story': 'قصة احترافية',
  'highlights': 'أبرز',
  'Live': 'يعيش',
  'reels': 'مقتطفات',
  'story': 'قصة',
  'Gallery': 'معرض',
  'send_code': 'إرسال الرمز',
  'forgot_password_title': 'نسيت كلمة المرور',
  'verify_code_title': 'التحقق من الكود',
  'verify': 'تحقق',
  'code_resend': 'إعادة إرسال الكود',
  'sec': 'ثانية',
  'did_code': 'لم تتلق رمز؟',
  'resend_code': 'إعادة إرسال الرمز',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'reset_password_title':
      'ستتمكن من تسجيل الدخول بكلمة المرور الجديدة مرة أخرى...',
  'new_password': 'كلمة مرور جديدة',
  'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
  'update_password': 'تحديث كلمة المرور',
  'skip': 'تخطي',
  'next': 'التالي',
  'welcome_to': 'مرحبا بكم في',
  'community': 'مجتمع',
  'get_started': 'ابدأ',
  'actions_for_today': 'إجراءات لهذا اليوم',
  'send': 'يرسل',
  'live_video': 'فيديو مباشر',
  'add_title': 'إضافة العنوان',
  'Add a title': 'إضافة عنوان',
  'start_time': 'وقت البدء',
  'schedule_live_video': 'جدولة الفيديو المباشر',
  'write_message': 'اكتب رسالة',
  'cancel': 'إلغاء',
  'end_video': 'نهاية الفيديو',
  'social': 'اجتماعي',
  'professional': 'احترافي',
  'new_highlight': 'قصه جديده',
  'title': 'عنوان',
  'Menu': 'القائمة',
  'Settings': 'الإعدادات',
  'Activity': 'نشاط',
  'QR Code': 'رمز الاستجابة السريعة',
  'Payments Method': 'طريقة المدفوعات',
  'About': 'حول',
  'Communities': 'مجتمعات',
  'Events': 'أحداث',
  'Member Guidlines': 'المبادئ التوجيهية للأعضاء',
  'MRC (Member Relation Center)': 'MRC (مركز علاقات الأعضاء)',
  'Profile Settings': 'إعدادات الملف الشخصي',
  'notifications': 'الإخطارات',
  'Privacy': 'خصوصية',
  'Security': 'أمن',
  'App Theme': 'موضوع التطبيق',
  'Followers': 'المتابعون',
  'Following': 'يتبع',
  'Matches': 'تطابق',
  'Edit Profile': 'تحرير الملف الشخصي',
  'Share Profile': 'مشاركة الملف الشخصي',
  'Contacts syncing': 'مزامنة جهات الاتصال',
  'Invite members': 'دعوة الأعضاء',
  'Remove': 'إزالة',
  'Unfollow': 'إلغاء المتابعة',
  'My Matches': 'مطابقه مع الاخرين',
  'Connect': 'يتصل',
  'Invite to Community Joined or Created': 'دعوة إلى المجتمع المنضم أو المنشأ',
  'Edit Profile Picture': 'تحرير صورة الملف الشخصي',
  'Username': 'اسم المستخدم',
  'Bio': 'بيو',
  'Posts': 'المشاركات',
  'Stories': 'قصص',
  'comments': 'تعليقات',
  'Story replies': 'تعليقات على القصه',
  'Calls': 'المكالمات',
  'Service Alerts': 'تنبيهات الخدمة',
  'Reminders & updates': 'التذكيرات والتحديثات',
  'Social Account Privacy': 'خصوصية الحساب الاجتماعي',
  'Messages replies on Stories': 'ردود الرسائل على القصص',
  'Privacy Alerts': 'تنبيهات الخصوصية',
  'Sensitive Content Controls': 'ضوابط المحتوى الحساسة',
  'Interactions': 'التفاعلات',
  'Blocked accounts': 'الحسابات المحظورة',
  'Muted accounts': 'حسابات صامتة',
  'Unrestricted': 'غير مقيد',
  'Unblock': 'إلغاء الحظر',
  'On it Profile Settings': 'عليه إعدادات الملف الشخصي',
  'Login Security': 'أمن تسجيل الدخول',
  'Login Activity': 'نشاط تسجيل الدخول',
  'Digital IDs': 'المعرفات الرقمية',
  'Cancellation & Refunds': 'الإلغاء واسترداد الأموال',
  'Trusty & Safety Disputes': 'نزاعات الثقة والسلامة',
  'Restricted accounts': 'الحسابات المقيدة',
  'One Time Payment': 'الدفع لمرة واحدة',
  'Scheduled Installment': 'القسط المقرر',
  'Service Vs Service': 'الخدمة مقابل الخدمة',
  'About ON it': 'عن ONit',
  'Privacy policy': 'سياسة الخصوصية',
  'Terms of use': 'شروط الاستخدام',
  'ONit brief explanation': 'ONit شرح موجز',
  'Member Guidelines': 'إرشادات الأعضاء',
  'Member Loyalty Program': 'برنامج ولاء الأعضاء',
  'Daily Post': 'البريد اليومي',
  'Congratulation!': 'مبروك!',
  'Claim Free Service Now': 'المطالبة بالخدمة المجانية الآن',
  'There will be a free service task for available for you if you upload daily posts to your social/professional/community accounts in your account.':
      'ستكون هناك مهمة خدمة مجانية لك متاح لك إذا قمت بالتحميل يوميا المشاركات إلى حساباتك الاجتماعية/المهنية/المجتمعية في حسابك.',
  'My Events': 'فعالياتي',
  'Attending': 'حضور',
  'Upcoming Events': 'الفعاليات القادمة',
  'party': 'احتفال',
  'Friends Forever Party': 'الأصدقاء إلى الأبد حفلة',
  'THU 26 May, 09:00 - FRI 27 May, 10:00':
      'الخميس 26 مايو، 09:00 - الجمعة 27 مايو، 10:00',
  'Recently Created Events': 'الأحداث التي تم إنشاؤها مؤخرا',
  'Satellite mega festival - 2023': 'مهرجان الأقمار الصناعية الضخم - 2023',
  'New York': 'نيويورك',
  'Sun 26 May, 9:00': 'الأحد 26 مايو، 9:00',
  'Intrested': 'مهتم',
  'Create Events': 'إنشاء الأحداث',
  'Create Events_normal': '#خطأ!',
  'Lorem ipsum dolor sit amet consectetur.':
      'Lorem ipsum dolor sit amet consectetur.',
  'Event Name': 'اسم الحدث',
  'Description': 'وصف',
  'Event Type': 'نوع الحدث',
  'Start Date': 'تاريخ البدء',
  'End Date': 'تاريخ الانتهاء',
  'Event Charge': 'رسوم الحدث',
  'eventDetails_mess_1': 'اقرأ المزيد..',
  'Intrested Users': 'المستخدمين المهتمين',
  'johndeo-123': 'كولدبلاي: موسيقى المجالات',
  'Coldplay : Music of the Spheres': 'كولدبلاي: موسيقى المجالات',
  'Gelora Bung Karno Stadium, Jakarta': 'ملعب جيلورا بونج كارنو، جاكرتا',
  'November 15 2023': '15 نوفمبر 2023',
  '50K+ Participants': '50K+ المشاركين',
  'Availability': 'التوفر',
  'Accounts': 'حسابات',
  'Join Communities': 'انضم إلى المجتمعات',
  'Popular Searches': 'عمليات البحث',
  'Community': 'مجتمع',
  '2.2k members': '2.2 K الأعضاء',
  'Private Community': 'مجتمع خاص',
  'You need to send a join request to this community admins...':
      'تحتاج إلى إرسال طلب انضمام إلى مسؤولي المجتمع هذا...',
  'Request to Join': 'طلب الانضمام',
  'Health Tips': 'نصائح صحية',
  'not_now': 'ليس الآن',
  'Join Community': 'انضم إلى المجتمع',
  'Send massage': 'إرسال رساله',
  'SEND': 'إرسال',
  'done': 'تم',
  'Theme': 'موضوع',
  'System Default': 'النظام الافتراضي',
  'Light': 'ضوء',
  'Dark': 'مظلم',
  'service_duration': 'مدة الخدمة',
  'service_duration:': 'مدة الخدمة:',
  'what_are_you:': 'تم التعديل',
  'help_us_tailor:': 'تحرير',
  'edited': 'تم التعديل',
  'edit': 'تحرير',
  'delete': 'حذف',
  'sending': 'إرسال...',
  'add_your_comment': 'أضف تعليقك...',
  'post': 'مشاركة',
  'press_and_hold_the_mic_to_record':
      'اضغط مع الاستمرار على الميكروفون لتسجيل الملاحظة الصوتية.',
  'and_other': 'وغيرها',
  'people_liked': 'أعجبت الناس',
  'liked_by': 'أحب الناس',
  'no_reels_available': 'لا توجد بكرات متاحة',
  'requested': 'طلب',
  'following': 'يتبع',
  'follow': 'يتبع',
  'others': 'الآخرين',
  'report': 'تقرير...',
  'are_you_sure_you_want_to_delete_this_reel': 'هل أنت متأكد، تريد حذف هذه البكرة',
  'please_go_to_setting_and_turn_on_turn_on_photos_and_media_permission': 'يرجى الانتقال إلى الإعداد وتشغيل الصور وإذن الوسائط',
  'gallery_not_accessed': 'لم يتم الوصول إلى المعرض',
  'send_message': 'إرسال رسالة:'
};
