Map<String, String> enLang = {
  "signUp": "Sign Up",
  "signup_title": "Create an account by filling in the following details",
  "lorem_ipsum": "Lorem ipsum dolor sit amet, consectetur",
  "first_name": "First Name",
  "last_name": "Last Name",
  "mobile_number": "Mobile Number",
  "country": "Country",
  "password": "Password",
  "confirm_password": "Confirm Password",
  "signIn": "Sign IN",
  "already_have_account": "Already have an account?",
  "email_address": "Email Address",
  "verify_code": "Verify Code",
  "please_check_verification": "Please , check your email. we’ve sent you the code at ",
  "Premium": "Premium",
  "password_validation": "Password must contain at least 8 characters, one capital letter, one number, and one special symbol",
  "subscribe_newsletter": "Subscribe to our Newsletter...",
  "agree_all": "I agree to all the",
  "term_condition": "Terms & Conditions",
  "welcome_back": "Welcome Back!",
  "signin_title": "You need to log in using your credentials",
  "dont_have_account": "Don't have an account?",
  "create_now": "Create Now",
  "forgot_password": "Forgot Password",
  'Service Provider (SP)': 'Service Provider (SP)',
  'Service Receiver (SR)': 'Service Receiver (SR)',
  'ON it Wallet': 'ON it Wallet',
  'ONit Portfolio': 'ONit Portfolio',
  'my_services': 'My Services',
  'my_bids': 'My Bids',
  'Browse Service →': 'Browse Service →',
  'Story Telling': 'Story Telling',
  'Pro Story': 'Pro Story',
  'highlights': 'Highlights',
  'Live': 'Live',
  'reels': 'Reels',
  'story': 'Story',
  'Gallery': 'Gallery',
  "send_code" : "Send Code",
  "forgot_password_title" : "Enter your email address and you will receive a verification code to reset your password...",
  "verify_code_title" : "Please, check your email. we’ve sent you the code at",
  'verify' : 'Verify',
  'code_resend' : 'Code resend in',
  'sec' : 'sec',
  'did_code' : 'Didn’t receive a code?',
  'resend_code' : 'Resend Code',
  'reset_password' : 'Reset Password',
  'reset_password_title' : 'You’ll be able to login with your new password once more...',
  'new_password' : 'New Password',
  'confirm_new_password' : 'Confirm New Password',
  'update_password' : 'Update Password',
  'skip' : 'Skip',
  'next' : 'Next',
  'welcome_to' : 'Welcome to',
  'community' : 'Community',
  'get_started' : 'Get Started',
  'actions_for_today' : 'Actions for Today',
  'send':'Send',
  'live_video':'Live Video',
  'add_title':'Add Title',
  'Add a title':'Add a title',
  'start_time':'Start Time',
  'schedule_live_video':'Schedule Live Video',
  'write_message':'Write message',
  'cancel':'Cancel',
  'end_video':'End Video',
  'social':'Social',
  'professional':'Professional',
  'new_highlight':'New Highlight',
  'title':'Title',
  'Menu':'Menu',
  'Settings':'Settings',
  'Activity':'Activity',
  'QR Code':'QR Code',
  'Payments Method':'Payments Method',
  'About':'About',
  'Communities':'Communities',
  'Events':'Events',
  'Member Guidlines':'Member Guidlines',
  'MRC (Member Relation Center)':'MRC (Member Relation Center)',
  'Profile Settings':'Profile Settings',
  'notifications':'Notifications',
  'Privacy':'Privacy',
  'Security':'Security',
  'App Theme':'App Theme',
  'Followers':'Followers',
  'Following':'Following',
  'Matches':'Matches',
  'Edit Profile':'Edit Profile',
  'Share Profile':'Share Profile',
  'Contacts syncing':'Contacts syncing',
  'Invite members':'Invite members',
  'Remove':'Remove',
  'Unfollow':'Unfollow',
  'My Matches':'My Matches',
  'Connect':'Connect',
  'Invite to Community Joined or Created':'Invite to Community Joined or Created',
  'Edit Profile Picture':'Edit Profile Picture',
  'Username':'Username',
  'Bio':'Bio',
  'Posts':'Posts',
  'Stories':'Stories',
  'comments':'Comments',
  'Story replies':'Story replies',
  'Calls':'Calls',
  'Service Alerts':'Service Alerts',
  'Reminders & updates':'Reminders & updates',
  'Social Account Privacy':'Social Account Privacy',
  'Messages replies on Stories':'Messages replies on Stories',
  'Privacy Alerts':'Privacy Alerts',
  'Sensitive Content Controls':'Sensitive Content Controls',
  'Interactions':'Interactions',
  'Blocked accounts':'Blocked accounts',
  'Muted accounts':'Muted accounts',
  'Unrestricted':'Unrestricted',
  'Unblock':'Unblock',
  'On it Profile Settings':'On it Profile Settings',
  'Login Security':'Login Security',
  'Login Activity':'Login Activity',
  'Digital IDs':'Digital IDs',
  'Cancellation & Refunds':'Cancellation & Refunds',
  'Trusty & Safety Disputes':'Trusty & Safety Disputes',
  'Restricted accounts':'Restricted accounts',
  'One Time Payment':'One Time Payment',
  'Scheduled Installment':'Scheduled Installment',
  'Service Vs Service':'Service Vs Service',
  'About ON it ':'About ON it ',
  'Privacy policy':'Privacy policy',
  'Terms of use':'Terms of use',
  'ONit brief explanation':'ONit brief explanation',
  'Member Guidelines':'Member Guidelines',
  'Member Loyalty Program':'Member Loyalty Program',
  'Daily Post':'Daily Post',
  'Congratulation!':'Congratulation!',
  'Claim Free Service Now':'Claim Free Service Now',
  'There will be a free service task for':'There will be a free service task for',
  'available for you if you upload daily':'available for you if you upload daily',
  'posts to your social/professional/community accounts in your account.':'posts to your social/professional/community accounts in your account.',
  'My Events':'My Events',
  'Attending':'Attending',
  'Upcoming Events':'Upcoming Events',
  'party':'Party',
  'John Deo':'John Deo',
  'Friends Forever Party':'Friends Forever Party',
  'THU 26 May, 09:00 - FRI 27 May, 10:00':'THU 26 May, 09:00 - FRI 27 May, 10:00',
  'Recently Created Events':'Recently Created Events',
  'Satellite mega festival - 2023':'Satellite mega festival - 2023',
  'New York':'New York',
  'THU 26 May, 09:00 ':'THU 26 May, 09:00 ',
  'Intrested':'Intrested',
  'Create Events':'+ Create Events',
  'Create Events_normal':'Create Events',
  'Lorem ipsum dolor sit amet consectetur.':'Lorem ipsum dolor sit amet consectetur.',
  'Event Name':'Event Name',
  'Description':'Description',
  'Event Type':'Event Type',
  'Start Date':'Start Date',
  'End Date':'End Date',
  'Event Charge':'Event Charge',
  'eventDetails_mess_1':'Integer id augue iaculis, iaculis orci ut, blandit quam. Donec in elit auctor, finibus quam in, phar. Proin id ligula dictum, covalis enim ut, facilisis massa. Mauris a nisi ut sapien blandit imperdi. Interdum et malesuada fames ac ante ipsum primis in faucibs. Sed posuere egestas nunc ut tempus. Fu ipsum dolor sit amet.',
  'Read More..':'Read More..',
  'Intrested Users':'Intrested Users',
  'johndeo-123':'johndeo-123',
  'Coldplay : Music of the Spheres':'Coldplay : Music of the Spheres',
  'Gelora Bung Karno Stadium, Jakarta':'Gelora Bung Karno Stadium, Jakarta',
  'November 15 2023':'November 15 2023',
  '50K+ Participants':'50K+ Participants',
  'Availability':'Availability',
  'Accounts':'Accounts',
  'Join Communities':'Join Communities',
  'Popular Searches':'Popular Searches',
  'Community':'Community',
  '2.2k members':'2.2k members',
  'Private Community':'Private Community',
  'You need to send a join request to this community admins...':'You need to send a join request to this community admins...',
  'Request to Join':'Request to Join',
  'Health Tips':'Health Tips',
  "You can’t just eat good food. You've got to talk about it, too...":"You can’t just eat good food. You've got to talk about it, too...",
  'not_now':'Not Now',
  'Join Community':'Join Community',
  'Send massage':'Send massage',
  'SEND':'SEND',
  'done':'Done',
  'Theme':'Theme',
  'System Default':'System Default',
  'Light':'Light',
  'Dark':'Dark',
  'service_duration':'Service Duration',
  'service_duration:':'Service Duration: ',
  "what_are_you":"What are you\nlooking for...",
  "help_us_tailor":"Help us tailor your\nexperience...",
  'edited':'Edited',
  'edit':'Edit',
  'delete':'Delete',
  'sending':'Sending...',
  'add_your_comment':'Add your comment...',
  'post':'Post',
  'press_and_hold_the_mic_to_record':'Press and hold the mic to record the voice note.',
  'and_other':'and other',
  'people_liked':'people liked',
  'liked_by':'Liked by',
  'no_reels_available':'No Reels Available',
  'requested':'Requested',
  'following':'Following',
  'follow':'Follow',
  'others':'Others',
  'report':'Report...',
  'are_you_sure_you_want_to_delete_this_reel':'Are you sure, You want to delete this reel',
  'please_go_to_setting_and_turn_on_turn_on_photos_and_media_permission':'Please go to setting and turn on photos and media permission',
  'gallery_not_accessed':'Gallery Not Accessed',
  "send_message":"Send message",
  'member':"Member",
  "notification_delete_successfully":"Notification delete successfully.",
  "follow_request":"Follow Request",
  "requested_to_follow_you":"Requested to follow you.",
  "follow_back":"Follow back",
  "confirm":"Confirm",
  "no_services_listed_yet":"No Services Listed Yet",
  "start_by_adding_your_services_so_we_can_find_your_task":"Start by adding your services so we can find your task as soon as possible!",
  "bid":"Bid!",
  "bidding_preview":"Bidding Preview",
  "security_door_lock":"Security Door Lock",
  "bidding_offer":"Bidding Offer",
  'submit_your_bid':'Submit Your Bid',
  'scheduled_installments':'Scheduled Installments',
  'proposal':'Proposal',
  'resume':'Resume',
  'your_resume_is_attached':'Your resume is attached',
  'your_bid_cannot_be_posted_because_you_do_not_have_sufficient_funds':'Your bid cannot be posted because you do not have sufficient funds',
  'deposit_fund':'Deposit Fund',
  'your_bid_has_been_successfully_submitted':'Your bid has been successfully submitted',
  'see_all_bids':'See All Bids',
  'upload_your_resume':'Upload your resume',
  'installment':'Installment',
  'bid_on_service':'Bid on Service',
  'service_budget':'Service Budget',
  'you_can_only_bid_with_in_those_values':'You can only bid with in those values.',
  'preview_bid':'Preview Bid',
  'select_service_duration':'Select Service Duration',
  'bidding_amount':'Bidding Amount',
  'bid_amount':'Bidding Amount: ',
  'writer_a_review':'write a review',
  'installment_name':'Installment Name',
  'installment_amount':'Installment Amount',
  'sort_by':'Sort by',
  'all':'All',
  'distance':'Distance',
  'service_price':'Service Price',
  'clear_all':'Clear All',
  'apply':'Apply',
  'financial_advisors':'Financial Advisors',
  'payment_type':'Payment Type',
  'service_category':'Service Category',
  'service_sub_category':'Service Sub-Category',
  'search_location':'Search Location',
  'on_it_transfer':'ON it Transfer',
  'total_balance':'Total balance',
  'deposit':'Deposit',
  'withdrawal':'Withdrawal',
  'withdrawal_schedule':'Withdrawal \n Schedule',
  'recent_activity':'Recent activity',
  'withdrawal_successfully':'Withdrawal Successfully',
  'withdrawal_schedule1':'Withdrawal Schedule',
  'transactions':'Transactions',
  'list_your_services':'List Your Services',
  'portfolio':'Portfolio',
  'you_can_add_up_to':'You can add up to',
  'services':'Services...',
  'service_type':'Service Type',
  'save_changes':'Save Changes',
  'badges':'Badges',
  'digital_ids':'Digital IDs/Certifications',
  'please_fill_all_details':'Please fill all details',
  'you_can_add_up_to_3_services.':'You can add up to 3 services.',
  'start_creating_your_on_it_portfolio':'Start creating your ON it Portfolio',
  'monetize_your_passion_by_talent':'Monetize your passion by listing your talents & qualifications and turning them into paid services',
  'create_portfolio':'Create Portfolio',
  'certifications':'Certifications',
  'listed_services':'Listed Services',
  'reviews_ratings':'Reviews & Ratings',
  'ratings':'Ratings',
  'bidding_details':'Bidding Details',
  'days':'days',
  'ongoing':'Ongoing',
  'completed':'Completed',
  'type':'Type',
  'service_status':'Service Status',
  'uploaded_files':'Uploaded Files',
  'service_completed_by_provider':'Service completed by provider.',
  'i_need_a_service':'I need a Service',
  'service_title':'Service Title',
  'you_can_add_up_to_3_packages':'You can add up to 3 packages...',
  'service_description':'Service Description',
  'choose_your_availability':'Choose your availability',
  'bidders_details':'Bidders Details',
  'posted':'Posted',
  'my_budget':'My Budget',
  'accept':'Accept',
  'pay_now':'Pay Now',
  'see_all_bids':'See All Bids',
  'your_bid_has_been_success':'Your bid has been successfully submitted',
  'if_you_want_to_see_the_bidder_details':'If you want to see the bidder details, you \nhave to pay 10 dollars',
  'bidding_budget:':'Bidding Budget: ',
  'category':'Category',
  'sub_category':'Sub-Category',
  'budget':'Budget',
  'service_completed_by_receiver':'Service completed by receiver.',
  'service_preview':'Service Preview',
  'discard':'Discard',
  'publish':'Publish',
  'subscription':'Subscription',
  'subscribe':'Subscribe',
  'choose_subscription_plan':'Choose Subscription Plan',
  'annualy':'Annualy',
  'standard_plan':'Standard Plan',
  '/month':'/Month',
  'perfect_for_starters':'Perfect for starters',
  'you_get':'You Get',
  'my_transactions':'My Transactions',
  'my_bidders':'My Bidders',
  'Post a Services →':'Post a Services →',
  'my_story':'My Story',
  'highlight':'Highlight',
  'service_provider':'Service Provider',
  'members':'members',
  'this_account_is_private':'This account is private',
  'follow_this_account_to_see_their_photos_and_videos':'Follow this account to see their photos and videos.',
  'Report':'Report',
  'Block':'Block',
  'restrict_and_mute':'Restrict and Mute',
  'thanks_for_letting_us_know':'Thanks for letting us know.',
  'account_history':'Account History',
  'my_circle':'My Circle',
  'search':'Search',
  'my_comments':'My Comments',
  'my_communities':'My Communities',
  'there_no_community_post':'There no Community Post',
  'there_are_no_liked_post_yet':'There are no Liked Post Yet!',
  'there_are_no_reels_saved_yet':'There are no Reels Saved Yet!',
  'there_are_no_post_saved_yet':'There are no post saved yet!',
  'saved_posts':'Saved Posts',
  'my_likes':'My Likes',
  'create_community':'Create Community',
  'community_name':'Community Name',
  'you_are_not_a_member_of_community':'You are not a member of community',
  'my_requests':'My Requests',
  '+Join Community':'+Join Community',
  'there_is_no_communities':'There is no Communities',
  'there_is_no_request_found':'There is no Request found',
  'Community!':'Community!',
  'please_enter_start_date_first':'please Enter Start Date First',
  'venue':'Venue',
  'link':'Link',
  'Upload_Image/Video':'Upload \n Image/Video',
  'show_more':'Show more',
  'show_less':'Show less',
  'attendings':'Attendings',
  'attending_users':'Attending Users',
  'you_had_not_created_events':'You had not created Events',
  'Virtual':'Virtual',
  'there_are_no_interested_events':'There are no Interested Events',
  'there_are_no_upcoming_and_recent_events':'There are no Upcoming and Recent Events',
  'Profile Un-Match Successfully':'Profile Un-Match Successfully',
  'The next time you bid on a service, or post a service, you\'ll receive one free service.':'The next time you bid on a service, or post a service, you\'ll receive one free service.',
  'Member Relation Center':'Member Relation Center',
  'Profile Updated':'Profile Updated',
  'Scan':'Scan',
  'Language':'Language',
  'Unmute':'Unmute',
  "You haven't restricted anyone":"You haven't restricted anyone",
  "You haven't blocked anyone":"You haven't blocked anyone",
  "Saved Log in Info":"Saved Log in Info",
  "Log out":"Log out",
  "Delete Account Permanently":"Delete Account Permanently",
  "yes_logout":"Yes, Log out",
  "are_you_sure_You_want_to_logout_this_ccount":"Are you sure, You want to logout this Account",
  "account_deletion_desc":"Account deletion is irreversible. Proceeding will erase all data. Please confirm this action carefully. If you need assistance, contact our team.",
  "no_bids_available":"No Bids Available",
  'there_is_no_follow_request':'There is no follow request',
  'there_is_no_notification':'There is no notification',
  'no_service_found':'No Servies Found',



  ///hintText

  "enter_first_name": "Enter Name",
  "enter_last_name": "Enter Last Name",
  "enter_mobile": "Enter Mobile",
  "enter_email": "Enter Email",
  "enter_password": "Enter Password",
  "select_country": "Select Country",
  'write_caption':'Write Caption',
  'select_post_category':'Select Post Category',
  'Pin Post on Your Profile':'Pin Post on Your Profile',
  'guide':'Guide',
  'Music':'Music',
  'Search Music':'Search Music',
  'new_reel':'New Reel',
  'preview':'Preview',
  'Edit Cover':'Edit Cover',
  'select_reel_category':'Select Reel Category',
  'Pin Reel on Your Profile':'Pin Reel on Your Profile',
  'select_story_category':'Select Story Category',
  'share_story':'Share Story',
  'Add Caption':'Add Caption',
  'your_followers_and_anyone_watching_will_see_this_title.':'Your followers and anyone watching will see this title.',
  'Add a Caption':'Add a Caption',
  'No Services Listed Yet':'No Services Listed Yet',
  'Start by adding your services so we can find your task as soon as possible!':'Start by adding your services so we can find your task as soon as possible!',
  'add_service_now':'Add Service Now →',
  'browse_services':'Browse Services',
  'see_all':'See All',
  'add':'Add',
  'save':'Save',
  'share':'Share',
  'add_story':'Add Story',
  'copy_link':'Copy Link',
  'messages':'Messages',
  'search_message':'Search message',
  'delete_messages':'Delete Messages',
  'are_you_sure_you_want_to_delete_these_selected_messages?':'Are you sure you want to delete these selected messages?',
  'yes_delete':'Yes, Delete',
  'write_your_message':'Write your message',
  'Event Description':'Event Description',
  'Select Start date':'Select Start date',
  'Select End date':'Select End date',
  '10\$':'10\$',
  'Message':'Message',
  'What are you looking for':'What are you looking for',
  "ago":"ago",
  "choose_countries":"Choose Countries",
  "search_country":"Search Country",
  "success":"Success",
  "allow_these_permissions":"Allow these permissions",
  "location":"Location",
  "location_permission_subtitle":"We will get your location",
  "notification":"Notification",
  "notification_permission_subtitle":"Get push notifications for everything you need to know about like post, reels, comment on post and reels",
  "allow_permission":"Allow Permission",
  'new':'New',
  'you_have_blocked_this_account':'You have blocked this account',
  'you_can_not_send_message_to':'You can not send message to',
  'you_replied_to_their_story':'You replied to their story',
  'replied_to_your_story':'Replied to your story',
  'no_posts_yet':'No posts yet',
  'enter_amount_in_usd':'Enter Amount in USD',
  'enter_insatallment_name':'Enter Installmet Name',
  'installment_delivery_date':'Installment Delivery Date',
  'select_date':'Select Date',
  'upload_previous_experience':'Upload Previous Experience',
  'no_address_found':'No address found',
  'saved_services':'Saved Services',
  'search_for_task':'Search for Task',
  'recent_posted_services':'Recently Posted Services',
  'please_select_service_type':'please select service type',
  'please_select_categories':'please select categories',
  'please_select_payment_type':'please select payment type',
  'please_select_services':'please select services',
  'filters':'Filters',
  'categories':'Categories',
  'sub_categories':'Sub-Categories',
  'location_and_remote':'Location and Remote',
  'enter_location':'Enter Location',
  'bidding_date':'Bidding Date: ',
  'service_receiver_budget:':'Service Receiver Budget: ',
  'service_receiver_budget':'Service Receiver Budget',
  'client':'Client: ',
  'payment':'Payment: ',
  'bidding_price':'Bidding Price: ',
  'delivery_date':'Delivery Date: ',
  'fixed':'Fixed',
  'price':'Price',
  'high_to_low':'High to Low',
  'low_to_high':'Low to High',
  'due_date':'Due Date',
  'latest':'Latest',
  'oldest_tasks':'Oldest Tasks',
  'closest_to_me':'Closest To Me',
  'service_details':'Service Details',
  'service_receiver_details':'Service Receiver Details',
  'paymnt':'Payment',
  'service_receiver_location':'Service Receiver Location',
  'hourly_payment':'Hourly Payment',
  'please_enter_location':'please enter location',
  'please_select_service_category':'please select service category',
  'please_select_service_sub_category':'please select service sub-category',
  'please_enter_title':'please enter title',
  'please_enter_description':'please enter description',
  'please_enter_amount':'please enter amount',
  'remote':'Remote',
  'my_location':'My Location',
  'view_profile':'View Profile',
  'reel':'Reel',
  'when':'When',
  'event_venue':'Event Venue',
  'paste_link':'Paste Link',
  'event_image':'Event Image',
  'report_desc':"Your reports is anonymous except if you're reporting an intellectual property infringements. If someone is in immediate danger, call the local emergency services - don't wait.",
  'no_members_yet':'No Members Yet',
  'review_and_ratings':'Reviews & Ratings',



  ///error
  "first_name_error": "Please Enter First Name",
  "last_name_error": "Please Enter Last Name",
  "email_name_error": "Please Enter Email",
  "phone_phone_error": "Please Enter Phone Number",
  "please_enter_password": "Please Enter Password",
  "please_enter_confirm_password": "Please Enter ConfirmPassword",
  "password_error": "Password Must be at least 8 character long",
  "password_not_matched": "Password Not Matched",
  "enter_valid_email": "Please Enter Valid Email",
  "something_went_wrong" : "Something Went Wrong",
  "no_internet_connection":"No Internet Connection",
  "connection_timeout":"Connection Timeout",
  "user_disabled":"User Disabled",
  "to_many_requests":"Too Many Requests",
  "invalid_phone_number":"Invalid Phone Number",
  "Invalid_code":"Invalid Code",
  "session_expired":"Session Expired",
  "quota_exceed":"Quota Exceed",
  "operation_not_allowed":"Operation Not Allowed",
  "error":"Error!",
  "warning":"Warning",
  "there_will_be_a_free_service_task":"There will be a free service task for \$4 available for you if you upload daily 10 posts to your social/professional/community accounts in your account.",
  'please_recode_your_voice_first':'Please recode your voice first',
  'audio_not_supported':'audio not supported',
  'sorry_we_are_having_trouble_playing_this_video':'Sorry, We are having trouble playing this video',
  'sorry_we_are_having_trouble_playing_this_story':'Sorry, We are having trouble playing this Story',
  'you_are_selecting_wrong_item':"You are selecting wrong item. (Choose Image or video)",
  'image_video':"Image/Video!,",
  'there_is_no_message':"There is no Messages",
  'there_is_no_community':"There is no Community",
  'please_upload_at_least_one_image_or_video':'please upload at least one image or video',
  'please_enter_service_duration':'please enter service duration',
  'please_enter_bidding_amount':'please enter bidding amount',
  'please_enter_bidding_amount_less_then':'please enter bidding amount less then',
  'please_enter_proposal':'please enter proposal',
  'no_post_available':'No post available, Create first post',
  'no_reel_available':'No reel available, Create first reel',
  'no_post_avail':'No post available',
  'no_reel_avail':'No reel available'
};
