name: artivaa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <3.13.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.5
  logger: ^2.0.1
  dio: ^5.0.3
  shared_preferences: ^2.1.0
  sizer: ^2.0.15
  hexcolor: ^2.0.7
  shimmer: ^2.0.0
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  camera: ^0.10.5+3
  simple_circular_progress_bar: ^1.0.2
  path_provider: ^2.0.15
  chat_bubbles: ^1.5.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  avatar_glow: ^2.0.2
  permission_handler: ^11.0.0
  readmore: ^2.2.0
  flutter_cached_pdfview: ^0.4.2

  # Date picker
  flutter_holo_date_picker: ^1.1.3
  intl: ^0.19.0
  flutter_gif: ^0.0.4
  spinner_date_time_picker: ^0.0.8
  image_stack: ^2.1.1
  flutter_blurhash: ^0.8.2

  # QR scanner
  mobile_scanner: ^3.5.5

  # Vibration
  vibration: ^1.8.4

  # Auth
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  onesignal_flutter: ^3.5.1

  fluttertoast: ^8.2.4
  crypto: ^3.0.2
  sign_in_with_apple: ^5.0.0
  easy_debounce: ^2.0.3
  photo_gallery: ^2.1.1
  photo_manager: ^2.8.1
  cached_network_image: ^3.3.0
  marquee: ^2.2.3
  device_marketing_names: ^0.8.0
  geocoding: ^2.0.0
  geolocator: ^7.6.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: any


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lottie/splashAnimation1.gif
    - assets/dummy_assets/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi/Satoshi-Light.otf
          weight: 400
        - asset: fonts/Satoshi/Satoshi-Regular.otf
          weight: 500
        - asset: fonts/Satoshi/Satoshi-SemiBold.otf
          weight: 600
        - asset: fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
