/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String cancelOnReelPage = "assets/icons/cancelOnReelPage.png";
  static const String icAboutInfo = "assets/icons/icAboutInfo.png";
  static const String icOnitTitle = "assets/icons/icOnitTitle.png";

  static const String customError = "assets/lottie/customError.json";
  static const String customError1 = "assets/lottie/customError1.json";
  static const String customSuccess = "assets/lottie/customSuccess.json";
  static const String customSuccess1 = "assets/lottie/customSuccess1.json";
  static const String splashAnimation1 = "assets/lottie/splashAnimation1.gif";

  static const String imgSplashText = "assets/images/imgSplashText.png";
  static const String imgLogo1 = "assets/images/imgLogo1.png";

  static const String icOnitDot = "assets/dummy_assets/icOnitDot.png";

}
